# Generated by Django 3.0.7 on 2020-08-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200718_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contentComment',
        ),
    ]
