# Generated by Django 3.0.7 on 2020-08-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200809_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contentComment',
            new_name='content',
        ),
    ]
